Remove parallelism for deployment

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -43,8 +43,9 @@ test:
     - ? >
         case ${CIRCLE_NODE_INDEX} in
         0)
-          printf "\n%s\n\n" "=== TEST nginx container with build site on host ==="
-          bundle exec rake test
+          set -e
+          printf "\n%s\n\n" "=== TEST nginx container [${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}] with rake test, index and build site on host ==="
+          bundle exec rake test && echo -e "\n ---> rake test is OK\n" || { echo " ---> rake test FAILED"; exit 1; }
           docker run --name "${DOCS_ELASTICSEARCH}" -p 9200:9200 -d "${DOCKER_HUB_ELASTICSEARCH}"
           sleep 10
           bundle exec rake index
@@ -61,7 +62,10 @@ test:
           $CIRCLE_PARALLEL && exit 0
           ;&
         1)
-          printf "\n%s\n\n" "=== TEST ruby container with build and serve site ==="
+
+          set -e
+          printf "\n%s\n\n" "=== TEST build ruby container [${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}] ==="
+
           docker build -t "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}" -f "${DOCKERFILE_RUBY}" .
           docker run --name "${DOCS_RUBY}" -p "${DOCS_RUBY_BIND_ADDRESS}:4000" --volume=$(pwd):"${DOCS_RUBY_VOL}" -it -d "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}"
           sleep 50
@@ -80,26 +84,49 @@ deployment:
   push_tag_develop:
     branch: develop
     commands:
-      - docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" -e "${DOCKER_LOGIN_EMAIL}" "${DOCKER_REGISTRY}"
-      - docker push "${DOCKER_IMAGE_ELASTICSEARCH}:${DOCKER_IMAGE_TAG}"
-      - docker push "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}"
-      - docker push "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}"
+      - ? >
+          case ${CIRCLE_NODE_INDEX} in
+          0)
+            set -e
+            docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" -e "${DOCKER_LOGIN_EMAIL}" "${DOCKER_REGISTRY}"
+            docker push "${DOCKER_IMAGE_ELASTICSEARCH}:${DOCKER_IMAGE_TAG}"
+            docker push "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}"
+            # Exit case statement if run in parallel else proceed to next case.
+            $CIRCLE_PARALLEL && exit 0
+            ;&
+          1)
+            set -e
+            docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" -e "${DOCKER_LOGIN_EMAIL}" "${DOCKER_REGISTRY}"
+            docker push "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}"
+            ;;
+          esac
   push_tag_master_stable_latest:
     branch: master
     commands:
-      - docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" -e "${DOCKER_LOGIN_EMAIL}" "${DOCKER_REGISTRY}"
-      - docker push "${DOCKER_IMAGE_ELASTICSEARCH}:${DOCKER_IMAGE_TAG}"
-      - docker push "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}"
-      - docker push "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}"
-      - docker tag "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_NGINX}:stable"
-      - docker tag "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_NGINX}:latest"
-      - docker tag "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_RUBY}:stable"
-      - docker tag "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_RUBY}:latest"
-      - docker push "${DOCKER_IMAGE_NGINX}:stable"
-      - docker push "${DOCKER_IMAGE_NGINX}:latest"
-      - docker push "${DOCKER_IMAGE_RUBY}:stable"
-      - docker push "${DOCKER_IMAGE_RUBY}:latest"
-
+      - ? >
+          case ${CIRCLE_NODE_INDEX} in
+          0)
+            set -e
+            docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" -e "${DOCKER_LOGIN_EMAIL}" "${DOCKER_REGISTRY}"
+            docker push "${DOCKER_IMAGE_ELASTICSEARCH}:${DOCKER_IMAGE_TAG}"
+            docker push "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}"
+            docker tag "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_NGINX}:stable"
+            docker tag "${DOCKER_IMAGE_NGINX}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_NGINX}:latest"
+            docker push "${DOCKER_IMAGE_NGINX}:stable"
+            docker push "${DOCKER_IMAGE_NGINX}:latest"
+            # Exit case statement if run in parallel else proceed to next case.
+            $CIRCLE_PARALLEL && exit 0
+            ;&
+          1)
+            set -e
+            docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" -e "${DOCKER_LOGIN_EMAIL}" "${DOCKER_REGISTRY}"
+            docker push "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}"
+            docker tag "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_RUBY}:stable"
+            docker tag "${DOCKER_IMAGE_RUBY}:${DOCKER_IMAGE_TAG}" "${DOCKER_IMAGE_RUBY}:latest"
+            docker push "${DOCKER_IMAGE_RUBY}:stable"
+            docker push "${DOCKER_IMAGE_RUBY}:latest"
+            ;;
+          esac
 
 general:
   artifacts:
